---
title: "NFL_attendance_linear_models"
author: "Alex MacCalman"
date: '`Sys.Date()`'
output: github_document
---
Builds a linear model and then uses cross validation  
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
This is about weeklty attendance to NFL games.  
```{r}
library(tidyverse)

attendance <- read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-02-04/attendance.csv")
standings <- read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-02-04/standings.csv")

#joing the datasets together
attendance_joined <- attendance %>% 
        left_join(standings, by = c("year", "team_name", "team"))
```

## Explore the data  
```{r}
#make a box plot of all the weekly attendance by playoffs
attendance_joined %>%
        filter(!is.na(weekly_attendance)) %>% 
        ggplot(aes(fct_reorder(team_name, weekly_attendance),
                weekly_attendance,
                fill = playoffs)) +
        geom_boxplot(outlier.alpha = 0.5) +
        coord_flip()

# make a overlay of distributions between the playoffs and nonplayoffs
attendance_joined %>% 
        distinct(team_name, year, margin_of_victory, playoffs) %>% 
        ggplot(aes(margin_of_victory, fill = playoffs)) +
        geom_histogram(position = "identity", alpha = 0.7)

# make a boxplot of the week to see if this variable influences weekly attendance.
attendance_joined %>% 
        mutate(week = factor(week)) %>% 
        ggplot(aes(week, weekly_attendance, fill = week)) +
        geom_boxplot(show.legend = FALSE, outlier.alpha = 0.7)
```

## Build dataset to use for modeling
```{r}
attendance_df <- attendance_joined %>% 
        filter(!is.na(weekly_attendance)) %>% 
        select(weekly_attendance, team_name, year, week,
               margin_of_victory, strength_of_schedule, playoffs)
```
## Train the model
```{r}
library(tidymodels)

attendance_split <- attendance_df %>% 
        initial_split(strata = playoffs)

nfl_train <- training(attendance_split)
nfl_test <- testing(attendance_split)


#build a ols linear regression
# first we set the modeling engine
lm_spec <- linear_reg() %>% 
        set_engine("lm")
# here we fit a model
lm_fit <- lm_spec %>% 
        fit(weekly_attendance ~.,
            data = nfl_train)

tidy(lm_fit) %>%  arrange(-estimate)


# now we will train a random forest
rf_spec <- rand_forest(mode = "regression") %>% 
        set_engine("ranger")
#fit model
rf_fit <- rf_spec %>% 
        fit(weekly_attendance ~.,
            data = nfl_train)

```

## Evaluate the models  
```{r}
# collect the results into a tibble
results_train <- lm_fit %>% 
        predict(new_data = nfl_train) %>% 
        mutate(truth = nfl_train$weekly_attendance,
               model = "lm") %>% 
        bind_rows(rf_fit %>% 
        predict(new_data = nfl_train) %>% 
        mutate(truth = nfl_train$weekly_attendance,
               model = "rf"))

results_test <- lm_fit %>% 
        predict(new_data = nfl_test) %>% 
        mutate(truth = nfl_test$weekly_attendance,
               model = "lm") %>% 
        bind_rows(rf_fit %>% 
        predict(new_data = nfl_test) %>% 
        mutate(truth = nfl_test$weekly_attendance,
               model = "rf"))

# calculate the rmse metric for each data set
results_train %>% 
        group_by(model) %>% 
        rmse(truth = truth, estimate = .pred)

results_test %>% 
        group_by(model) %>% 
        rmse(truth = truth, estimate = .pred)

# visualize the predicted versus truth
results_test %>% 
        mutate(train = "testing") %>% 
        bind_rows(results_train %>% 
                          mutate(train = "training")) %>% 
        ggplot(aes(truth, .pred, color = model)) +
        geom_abline(lty = 2, color = "grey80", size = 1.5) +
        geom_point(alpha = 0.5) +
        facet_wrap(~train)
        
```
Models did not perform well. Now we will try cross validation.  
```{r}
set.seed(1234)
nfl_folds <- vfold_cv(nfl_train, strata = playoffs)

rf_res <- fit_resamples(
        weekly_attendance ~ .,
        rf_spec,
        nfl_folds,
        control = control_resamples(save_pred = TRUE)
)
#collect metrics
rf_res %>%
        collect_metrics()
     
#now let's visualize
rf_res %>% 
        unnest(.predictions) %>% 
        ggplot(aes(weekly_attendance, .pred, color = id)) +
        geom_abline(lty = 2, color = "grey80", size = 1.5) +
        geom_point(alpha = 0.5)
```

