---
title: "food_hyperparameter_tuning"
author: "Alex MacCalman"
date: "8/30/2020"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
Our modeling goal here is to predict which countries are Asian countries and which countries are not, based on their patterns of food consumption in the eleven categories.  
```{r}
library(tidyverse)
#import the data
food_consumption <- readr::read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-02-18/food_consumption.csv")
library(countrycode)
library(janitor)
```
## Explore the data  
```{r}
#assign a continent to each of the countires
food <- food_consumption %>% 
        mutate(continent = countrycode(country,
                                       origin = "country.name",
                                       destination = "continent")) %>% 
        select(-co2_emmission) %>% 
        pivot_wider(names_from = food_category,    #pivot wider to put all food in columns
                    values_from = consumption) %>% 
        clean_names() %>% 
        mutate(asia = case_when(continent == "Asia" ~ "Asia", #create the response to be Asia or Other
                                TRUE ~ "Other")) %>% 
        select(-country, -continent) %>% 
        mutate_if(is.character, factor)

#Explore the numeric data
library(GGally)
#when we only have numeric values to see a scatter matrix, tell which cols have numeric values
ggscatmat(food, columns = 1:11, color = "asia", alpha = 0.6)
# the patterns show a lot of interactions making a random forest an good modeling technique for this type of data.

```
## Tune hyperparameters  
```{r}
library(tidymodels)
set.seed(1234)
#set up a bootstrap sample
food_boot <- bootstraps(food, times = 30)
# set the specification
rf_spec <- rand_forest(mode = "classification",
            mtry = tune(),
            trees = 1000,
            min_n = tune()) %>% 
        set_engine("ranger")

rf_grid <- tune_grid(
        asia ~ .,
        model = rf_spec,
        resamples = food_boot
)
```
Now that we have our grid, we will collect the metrics.  
```{r}
rf_grid %>% 
        collect_metrics()

rf_grid %>% 
        show_best("roc_auc")


```




